name: Update TryHackMe Badge

on:
  schedule:
    - cron: '0 0 * * *'  # Runs once every day at midnight (UTC)
  workflow_dispatch:     # Lets you run it manually

permissions:
  contents: write

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get TryHackMe badge
        uses: DhanushNehru/tryhackme-badge-action-workflow@v1
        with:
          username: 'dininduga'
          image_path: 'assets/tryhackme-badge.png'

      - name: Save badge to repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update TryHackMe badge
          file_pattern: assets/tryhackme-badge.png
